#!/usr/bin/env python3
"""Convert a Slack member export (JSON) into data/employees.local.js.

Usage:
    python3 scripts/import_employees.py path/to/random_channel_members.json

The output is git-ignored because the repository is public. Keep the export
itself outside the repo too.

Accepts a list of members, or an object with a "members" list (Slack
users.list / conversations.members + users.info style). Bots, deleted and
guest-less placeholder accounts are skipped. Cards already listed in
data/employees.local.js are kept when their id matches.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
# Real names stay out of git: this file is git-ignored and loads on top of data/employees.js.
OUT = ROOT / "data" / "employees.local.js"


def pick(*values):
    for v in values:
        if isinstance(v, str) and v.strip():
            return v.strip()
    return ""


def existing_cards():
    if not OUT.exists():
        return {}
    m = re.search(r"window\.EMPLOYEES = (\[.*\]);", OUT.read_text(encoding="utf-8"), re.S)
    if not m:
        return {}
    try:
        return {e["id"]: e.get("cards", []) for e in json.loads(m.group(1))}
    except (json.JSONDecodeError, KeyError, TypeError):
        return {}


def members_from(data):
    if isinstance(data, dict):
        for key in ("members", "users", "data", "results"):
            if isinstance(data.get(key), list):
                return data[key]
        raise SystemExit("Couldn't find a list of members in the JSON.")
    return data


def main(path):
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    cards = existing_cards()
    out, seen = [], set()
    for m in members_from(data):
        if isinstance(m, str):
            m = {"name": m}
        if m.get("deleted") or m.get("is_bot") or m.get("is_app_user") or m.get("id") == "USLACKBOT":
            continue
        p = m.get("profile") or {}
        name = pick(m.get("real_name"), p.get("real_name"), p.get("display_name"), m.get("name"), m.get("full_name"))
        if not name:
            continue
        # A bare "name" is the full name in some exports, so only use it as a handle when real_name exists.
        handle = pick(p.get("display_name"), m.get("username"), m.get("name") if m.get("real_name") else "")
        emp_id = pick(m.get("id"), m.get("user_id"), m.get("email"), p.get("email")) or re.sub(r"\W+", "-", name.lower())
        if emp_id in seen:
            continue
        seen.add(emp_id)
        emp = {
            "id": emp_id,
            "name": name,
            "title": pick(p.get("title"), m.get("title")),
            "slack": f"@{handle}" if handle and handle != name else "",
            "avatar": pick(m.get("avatar_url"), p.get("image_192"), p.get("image_72")),
            "profileUrl": pick(m.get("profile_url")),
            "cards": cards.get(emp_id, []),
        }
        out.append({k: v for k, v in emp.items() if v or k == "cards"})
    out.sort(key=lambda e: e["name"].lower())
    body = ",\n".join("  " + json.dumps(e, ensure_ascii=False) for e in out)
    OUT.write_text(
        f"// Generated by scripts/import_employees.py from {Path(path).name}.\n"
        "// Each employee lists card ids from data/cards.js. Git-ignored: never commit real names.\n"
        "window.EMPLOYEES_SAMPLE = false;\n"
        f"window.EMPLOYEES = [\n{body}\n];\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(out)} employees to {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
