#!/usr/bin/env python3
"""Convert the Indian credit card catalogue (.xlsx) into data/cards.js.

Usage:
    pip install openpyxl
    python3 scripts/import_cards.py data/Indian_Credit_Card_Catalogue_v0_5.xlsx

Reads the "Cards" sheet (columns: Issuer, Card Name, Category, Status, Network,
Source, Notes, Search Alias, Official URL, Last Verified, Employee Catalogue,
Co-branded) and keeps rows marked "Yes" in Employee Catalogue.
"""
import json
import re
import sys
from pathlib import Path

import openpyxl

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "data" / "cards.js"
# Optional {card id: image path or URL}; see scripts/fetch_card_images.py.
IMAGES = ROOT / "data" / "card-images.json"


def slug(text):
    return re.sub(r"[^a-z0-9]+", "-", text.lower().replace("+", " plus")).strip("-")


def clean(value):
    return str(value).strip() if value is not None else ""


def main(path):
    wb = openpyxl.load_workbook(path, read_only=True, data_only=True)
    ws = wb["Cards"]
    rows = ws.iter_rows(values_only=True)
    header = [clean(h) for h in next(rows)]
    col = {name: i for i, name in enumerate(header)}

    images = json.loads(IMAGES.read_text(encoding="utf-8")) if IMAGES.exists() else {}
    cards, seen = [], set()
    for raw in rows:
        row = lambda key: raw[col[key]] if col[key] < len(raw) else None
        issuer, name = clean(row("Issuer")), clean(row("Card Name"))
        if not issuer or not name:
            continue
        if clean(row("Employee Catalogue")).lower() not in ("yes", ""):
            continue
        card_id = slug(f"{issuer} {name}")
        if card_id in seen:
            continue
        seen.add(card_id)

        # "To be verified by variant" means unknown; "Visa / Mastercard - verify variant" keeps the prefix.
        network = clean(row("Network"))
        network = "" if network.lower().startswith("to be verified") else network.split(" - ")[0].strip()

        aliases = [a.strip() for a in clean(row("Search Alias")).split(";")]
        aliases = [a for a in aliases if a and a.lower() != name.lower()]

        cards.append({
            "id": card_id,
            "issuer": issuer,
            "name": name,
            "category": clean(row("Category")) or "Rewards / General",
            "network": network,
            "coBranded": row("Co-branded") == 1,
            "aliases": aliases,
            "url": clean(row("Official URL")),
            "status": clean(row("Status")),
        })
        if images.get(card_id):
            cards[-1]["image"] = images[card_id]

    source = Path(path).name
    body = json.dumps(cards, ensure_ascii=False, indent=1)
    OUT.write_text(
        f"// Generated by scripts/import_cards.py from {source}. Do not edit by hand.\n"
        f"window.CARD_CATALOGUE = {body};\n",
        encoding="utf-8",
    )
    with_images = sum(1 for c in cards if c.get("image"))
    print(f"Wrote {len(cards)} cards ({with_images} with images) to {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
